print('What do you get when you cross a snowman with a vampire?')
input()
print('Frostbite')
print()
print('What do dentists call an astronaut\'s cavity?')
input()
print('A black hole')
print()
print('Knock Knock')
input()
print('Who\'s there?')
input()
print('Interupting cow.')
input()
print('Interupting cow wh', end='')
print('-MOO!!!')
      
